name: Autograding

on:
  push:
    branches:
      - main

jobs:
  testAppliance:
    name: Test Appliance Class
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Gradle
        run: ./gradlew build -x test
      - name: Run Appliance tests
        run: ./gradlew test --tests "com.example.ApplianceTest"

  testRefrigerator:
    name: Test Refrigerator Class
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Gradle
        run: ./gradlew build -x test
      - name: Run Refrigerator tests
        run: ./gradlew test --tests "com.example.RefrigeratorTest"

  testBonus:
    name: Test Bonus Features
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Gradle
        run: ./gradlew build -x test
      - name: Run Bonus tests
        run: ./gradlew test --tests "com.example.BonusTest"
